# Import

In [11]:
import random
import numpy as np
import math

# Tweak Stato

In [12]:
def tweak(sol):
    
    sol_copy = np.copy(sol)
    
    # scegli random due colonne distinte
    x = random.randint(0,DIMENSIONE-1)
    y = random.randint(0,DIMENSIONE-1)
    while x==y:
        y = random.randint(0,DIMENSIONE-1)
        
    # scambia le due colonne
    temp = sol_copy[y]
    sol_copy[y] = sol_copy[x] 
    sol_copy[x] = temp
    
    return sol_copy

# Inizializzazione Stato

In [13]:
def inizializza(sol):
    
    # shake shake shake
    for c in range(0,DIMENSIONE-1):
        sol = tweak(sol)
    return sol

# Calcolo dell'energia (numero attacchi)

In [14]:
def energia(stato):
    
    # definizione della scacchiera N x N
    board  = [[0] * DIMENSIONE for i in range(DIMENSIONE)] 
    
    # inserimento delle regine ('Q') nelle loro posizioni sulla scacchiera
    for i in range(0,DIMENSIONE):
        board[stato[i]][i] ='Q'
        
    # spostamenti possibili sulla scacchiera
    dx = [-1,1,-1,1]
    dy = [-1,1,1,-1]
    
    # inizializzazione numero di attacchi (diretti o indiretti)
    conflitti = 0

    for i in range(0,DIMENSIONE):       
        x = stato[i]
        y = i
        
        # verifica attacchi sulle diagonali       
        for j in range(0,4):
            tempx = x
            tempy = y
            while (True):
                tempx = tempx + dx[j]           # spostamento sull'asse x
                tempy = tempy + dy[j]           # spostamento sull'asse y
                if ((tempx < 0) or 
                    (tempx >= DIMENSIONE) or
                    (tempy < 0) or 
                    (tempy >= DIMENSIONE)):
                    break                       # si esce se lo spostamento va fuori la scacchiera
                if (board[tempx][tempy]=='Q'):
                    conflitti = conflitti + 1   # aggiornamento numero di attacchi
    return conflitti

# Stampa scacchiera

In [15]:
def stampa(sol):
    
    board = [[0] * DIMENSIONE for i in range(DIMENSIONE)] 

    for x in range(0,DIMENSIONE):
        board[sol[x]][x] = 'Q'
    print("SCACCHIERA", '\n')
    for x in range(0,DIMENSIONE):
        for y in range(0,DIMENSIONE):
            if(board[x][y]=='Q'):
                print("Q   ",end=''),
            else:
                print(".   ",end=''),
        print("\n")
    print("\n\n")

# Algoritmo Simulated Annealing

In [32]:
def simulated_annealing():
    
    # impostazione dello stato iniziale
    current = inizializza(range(0,DIMENSIONE))
    current_energy = energia(current)
    print(current)
    
    # inizializzazione best
    best = current
    best_energy = current_energy

    temperature = TEMPERATURA_INIZIALE

    while (temperature > TEMPERATURA_FINALE and best_energy != 0):
        for step in range(0,STEPS_PER_CHANGE):
            useNew = False
            next_state = tweak(current)                # scelta random dello stato successore nel neighbourhood
            next_state_energy = energia(next_state)    # valutazione dell'energia dello stato successore
    
            if (next_state_energy < current_energy):   # se il successore è migliore lo accettiamo
                useNew = True
            else:
                delta = next_state_energy - current_energy
                metropolis = math.exp(-delta/temperature)  # calcolo probabilità di accettazione
                test = random.random()
                if (test < metropolis):                # se il numero random è minore della probabilità ...
                    useNew = True                      # ... accettiamo il nuovo stato 
                    
            # se abbiamo deciso di accettare il nuovo stato:   
            if (useNew):
                # impostalo come stato ed energia correnti
                current = next_state
                current_energy = next_state_energy
            
                # se è anche il migliore segna il record
                if (current_energy < best_energy):
                    best = current
                    best_energy = current_energy
        
        # diminuisci la temperatura, senza mai arrivare a zero
        temperature = temperature * ALFA
        
    return(best)

## Esecuzione dell'algoritmo

In [22]:
# Impostazione parametri

TEMPERATURA_INIZIALE = 30
TEMPERATURA_FINALE = 0.2
ALFA = 0.99
STEPS_PER_CHANGE = 100

DIMENSIONE = 20   # dimensione dei lati della scacchiera N x N (dove N è la DIMENSIONE)

In [33]:
for i in range(10):
    soluzione = simulated_annealing()
    print(energia(soluzione))

[17  1 19 10 16  8 15  3 11  9  7 12  6  5 14  2  0  4 18 13]
0
[18  1 19 11  9  3 16  7  8  5 10 15 13  4 12  6 17  0  2 14]
0
[16  1  2 17  8 19 15  3 11  5  7  9 12 13  4  0 18  6 14 10]


KeyboardInterrupt: 

In [30]:
soluzione

0


array([ 3, 15, 17,  4, 13,  7, 12,  6, 19, 16, 18,  0,  9, 11,  1,  8, 10,
        5,  2, 14])

In [20]:
soluzione

array([ 2,  8, 13, 17, 12, 14,  1,  5, 18,  9,  4, 16, 11,  0, 15,  6, 19,
        7, 10,  3])